---
title: "R Notebook"
output: html_notebook
---

# Pacotes 

```{r}
if (!require("quantreg")) install.packages("quantreg")
if (!require("stargazer")) install.packages("stargazer")
if (!require("skedastic")) install.packages("skedastic")
if (!require("lmtest")) install.packages("lmtest")
if (!require("sandwich")) install.packages("sandwich")
```

# Análise Descritiva

## IIE

```{r}
ggplot()+
  geom_density(data = educacao_muni %>% mutate(ano = as.character(ano)),
               aes(x = iie, group = ano, fill = ano), alpha = 0.5)+
  theme_minimal()
```

```{r}
# mapa iie
ggplot()+
  geom_sf(data = educacao_muni %>% sf::st_as_sf(), aes(fill = iie), colour = NA)+
  geom_sf(data = estados, fill = NA)+
  scale_fill_viridis_c(option = "G")+ # mako 
  theme_minimal()+
  facet_wrap(~ano)
```

## IDEB

```{r}
ggplot()+
  geom_density(data = educacao_muni %>% mutate(ano = as.character(ano)),
               aes(x = ideb, group = ano, fill = ano), alpha = 0.5)+
  theme_minimal()
```

```{r}
# mapa ideb
ggplot()+
  geom_sf(data = educacao_muni %>% sf::st_as_sf(), aes(fill = ideb), colour = NA)+
  geom_sf(data = estados, fill = NA)+
  scale_fill_viridis_c(option = "A", na.value = NA)+ # mako 
  theme_minimal()+ 
  facet_wrap(~ano)
```

# Regressão quantílica

## Logaritimizando  
```{r}
educacao_qr <- educacao_muni %>%
  mutate(
    ln_ideb = log(ideb),
    ln_iie = log(iie),
    # ln_desp_pc = log(desp_educ_pc_defl),
    ln_inv_pub = log(inv_pub_educ_defl),
    ln_pib_pc = log(pib_muni_pc)
  ) %>%
  filter(
    # ln de zero é indeterminado!!!!!
    is.finite(ln_ideb),
    is.finite(ln_iie),
    # is.finite(ln_desp_pc),
    is.finite(ln_inv_pub),
    is.finite(ln_pib_pc)
  )
```

## MQO 

```{r}
mqo <- lm(ln_ideb ~ ln_iie + ln_inv_pub + ln_pib_pc, #+ ln_desp_pc,
          data = educacao_qr)
```

```{r}
# heterocedasticidade
skedastic::white(mqo)

# matriz ROBUSTA de cov-var
vcov_white <- vcovHC(mqo, type = "HC0")

# se robusto
se_white <- sqrt(diag(vcov_white))
```

```{r}
modelsummary::modelsummary(
  mqo, 
  statistic = "conf.int",     # intervalos de confiança
  coef_map = c("ln_iie" = "Log(IIE)",
               "ln_inv_pub" = "Log(Investimento Público)",
               "ln_pib_pc" = "Log(PIB per capita)"),
  gof_omit = "AIC|BIC|Log.Lik", 
  stars = TRUE,                
  output = "html"          
)
```


## Quantílica

```{r}
modelo_q10 <- rq(ln_ideb ~ ln_iie + ln_inv_pub + ln_pib_pc, tau = 0.1, data = educacao_qr)
modelo_q25 <- rq(ln_ideb ~ ln_iie + ln_inv_pub + ln_pib_pc, tau = 0.25, data = educacao_qr)
modelo_q50 <- rq(ln_ideb ~ ln_iie + ln_inv_pub + ln_pib_pc, tau = 0.50, data = educacao_qr)
modelo_q75 <- rq(ln_ideb ~ ln_iie + ln_inv_pub + ln_pib_pc, tau = 0.75, data = educacao_qr)
modelo_q90 <- rq(ln_ideb ~ ln_iie + ln_inv_pub + ln_pib_pc, tau = 0.9, data = educacao_qr)
```

```{r}
modelsummary::modelsummary(
  list("Quantil 10%" = modelo_q10, 
       "Quantil 25%" = modelo_q25,
       "Quantil 50%" = modelo_q50,
       "Quantil 75%" = modelo_q75, 
       "Quantil 90%" = modelo_q90),
  statistic = "conf.int",     # intervalos de confiança
  coef_map = c("ln_iie" = "Log(IIE)",
               "ln_inv_pub" = "Log(Investimento Público)",
               "ln_pib_pc" = "Log(PIB per capita)"),
  gof_omit = "AIC|BIC|Log.Lik", 
  stars = TRUE,                
  output = "html"          
)
```

